# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\uic\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.setWindowModality(QtCore.Qt.NonModal)
        MainWidget.resize(409, 171)
        MainWidget.setMinimumSize(QtCore.QSize(0, 150))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        MainWidget.setWindowOpacity(1.0)
        MainWidget.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_x = QtWidgets.QPushButton(MainWidget)
        self.btn_x.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_x.setMouseTracking(True)
        self.btn_x.setStyleSheet("QPushButton#btn_x {\n"
"    border-image: url(:/images/btn_x.png);\n"
"}\n"
"\n"
"QPushButton#btn_x:hover {\n"
"    border-image: url(:/images/btn_x2.png);\n"
"}\n"
"")
        self.btn_x.setText("")
        self.btn_x.setObjectName("btn_x")
        self.horizontalLayout.addWidget(self.btn_x)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.combobox_monitor = QtWidgets.QComboBox(MainWidget)
        self.combobox_monitor.setObjectName("combobox_monitor")
        self.gridLayout.addWidget(self.combobox_monitor, 0, 1, 1, 1)
        self.label_combobox_monitor = QtWidgets.QLabel(MainWidget)
        self.label_combobox_monitor.setMinimumSize(QtCore.QSize(80, 0))
        self.label_combobox_monitor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_combobox_monitor.setObjectName("label_combobox_monitor")
        self.gridLayout.addWidget(self.label_combobox_monitor, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_hsilder_brightness = QtWidgets.QLabel(MainWidget)
        self.label_hsilder_brightness.setObjectName("label_hsilder_brightness")
        self.gridLayout_3.addWidget(self.label_hsilder_brightness, 0, 0, 1, 1)
        self.hsilder_brightness = QtWidgets.QSlider(MainWidget)
        self.hsilder_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.hsilder_brightness.setObjectName("hsilder_brightness")
        self.gridLayout_3.addWidget(self.hsilder_brightness, 0, 1, 1, 1)
        self.spinbox_brightness = QtWidgets.QSpinBox(MainWidget)
        self.spinbox_brightness.setObjectName("spinbox_brightness")
        self.gridLayout_3.addWidget(self.spinbox_brightness, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(MainWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_show_monitor_info = QtWidgets.QPushButton(MainWidget)
        self.btn_show_monitor_info.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_show_monitor_info.setObjectName("btn_show_monitor_info")
        self.gridLayout_2.addWidget(self.btn_show_monitor_info, 0, 0, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(MainWidget)
        self.btn_exit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout_2.addWidget(self.btn_exit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Brightness Ctrl"))
        self.label.setText(_translate("MainWidget", "Brightness Control"))
        self.label_combobox_monitor.setText(_translate("MainWidget", "　显示器："))
        self.label_hsilder_brightness.setText(_translate("MainWidget", "亮度："))
        self.btn_show_monitor_info.setText(_translate("MainWidget", "显示器信息"))
        self.btn_exit.setText(_translate("MainWidget", "退出"))
import res_rc
